# Generated by Django 3.0.1 on 2019-12-26 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbackpost',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('txtfield', models.CharField(max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.date(2019, 12, 26))),
                ('time', models.TimeField(blank=True, default='08:18:02')),
            ],
        ),
    ]
